apiVersion: v1
kind: ServiceAccount
metadata:
  name: aerosphere-app-sa
  namespace: aerosphere-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aerosphere-app-role
  namespace: aerosphere-prod
rules:
# Least privilege: apps only need to read specific secrets and configmaps
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aerosphere-app-rolebinding
  namespace: aerosphere-prod
subjects:
- kind: ServiceAccount
  name: aerosphere-app-sa
  namespace: aerosphere-prod
roleRef:
  kind: Role
  name: aerosphere-app-role
  apiGroup: rbac.authorization.k8s.io
