apiVersion: v1
kind: Namespace
metadata:
  name: aerosphere-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: aerosphere-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
